### PR TITLE
Added Docker support

### PR DESCRIPTION
**Pull request by vinanrra**
Still need few things that i don't know like:

Which folder should be persistent to avoid missing:
- [ ] Challenges
- [ ] User database

### CODE REVIEW

**Comment by vinanrra** [comment]
One more thing need it should be an automatization for new builds like this at Docker Hub:

imagen

**Comment by surajcm** [comment]
Currently, the data is not persistent, because I am using an in-memory database (HSQL DB). I have heard that another in-memory database (H2) supports persisting of data as a file. It may be a straightforward migration, I will do it shortly. 

And, thanks a lot for the pull request 👍 . I will pull these changes in. At least we can test this without the persistent changes.

**Comment by vinanrra** [comment]
Mention to me you switch to persisting data and i will add support for volumes, and remember to link your Github repository with the Docker Hub to automate the builds, because i cant do that, because i dont have perms in this repo, so you are the only one able to do it.

**Comment by surajcm** [comment]
I linked the GitHub with docker hub, and the docker image is now available, you can get it on [https://hub.docker.com/r/surajcm/darkhold](https://hub.docker.com/r/surajcm/darkhold)

I will let you know once the data persistence is ready 👍

**Comment by surajcm** [comment]
@vinanrra , I have pushed the changes required for data persistence. It worked in my local, but I think we need to update the DockerFile to have the local database file inside the docker image.  I am keeping the database file at `/tmp/db/` , currently it is a file named `darkhold.mv.db`. I guess maybe we should have a line like the below one in the DockerFile

```
COPY /tmp/db/* /tmp/db/
```

**Comment by vinanrra** [comment]
I will check later the image and see what i need to change.

There database is store at /tmp/db name as darkhold.mv.db `/tmp/db/darkhold.mv.db ` right?

**Comment by surajcm** [comment]
Yes, you are right. The database is used for user information, challenges and questions.

**Pull request merged**
