### PR TITLE
Added volume for persistant database and improvements

### PR DESCRIPTION
**Pull request by vinanrra**

### CODE REVIEW

**Comment by vinanrra** [comment]
I have added a Docker-compose and added Docker link to README, so people can find it easier.

**Comment by vinanrra** [comment]
I have tested and it's working without any problem.

**Comment by vinanrra** [comment]
One thing that I would like to do its add some changes at the wiki with Docker installation, but I am unable to find where should I do it.

**Comment by surajcm** [comment]
Thank you for the changes 👍 
For wiki, actually, it works as a different repo, you may have to clone it at the url `https://github.com/surajcm/darkhold.wiki.git` and then edit it.

**Comment by vinanrra** [comment]
> 
> 
> Thank you for the changes 👍
> For wiki, actually, it works as a different repo, you may have to clone it at the url `https://github.com/surajcm/darkhold.wiki.git` and then edit it.

Please change Wiki permissions, you can follow this link because i am unable to push my changes :/

https://docs.github.com/en/communities/documenting-your-project-with-wikis/changing-access-permissions-for-wikis

**Comment by surajcm** [comment]
Done !!!

**Pull request merged**
